### PR TITLE
Added nuts Issuer for test/demo purposes. Used for agb attributes

### PR DESCRIPTION
**Pull request by woutslakhorst**
Added nuts Issuer for test/demo purposes. The AGB-code is used by healthcare organisation to uniquely identify care providers. Nuts is an initiative for standardising the flow of healthcare data in the Netherlands. More information on https://nuts.nl.

I signed the root with the given sk.pem. Schememanager Verification succeeded.

### CODE REVIEW

**Comment by confiks** [comment]
Looks good. The only potential issue I have with it, is that it doesn't describe itself as a demo credential. All current credential except irmatube (which is a demo platform demo in itself) identify themselves as demo credentials in the name.

**Comment by sietseringers** [comment]
Are you planning to use this issuer and/or credential type (as it is or modified) in production (i.e. in the `pbdf` scheme)? If so it would be best if you prepend their names with "Demo" (example [here](https://github.com/privacybydesign/irma-demo-schememanager/blob/master/alliander/description.xml) and [here](https://github.com/privacybydesign/irma-demo-schememanager/blob/master/alliander/Issues/connection/description.xml)). Otherwise the production issuers and credentialtypes won't be sufficiently distinguishable from their testing (untrusted) equivalents.

**Comment by woutslakhorst** [comment]
Will do

**Comment by woutslakhorst** [comment]
@sietseringers @confiks done

**Pull request merged**
