### PR TITLE
Added discipl-pra issuer with credentials for two experimental demo's

### PR DESCRIPTION
**Pull request by stanvanlier**

### CODE REVIEW

**Comment by ivard** [comment]
Hi @stanvanlier,

Long time no see. Nice to see that you want to do something with Yivi. Can you tell a little bit more about the demo you have planned? That gives us a bit more context. Then we can give you better feedback.

**Comment by stanvanlier** [comment]
Hi @ivard,

Indeed! We are building an application which uses personal information from multiple sources. Some sources (such as mijnpensioenoverzicht.nl) make this data available as a json file. We are looking into other options which are more convenient and secure.

This pull request contains two ways of saving mijnpensioenoverzicht.json as Yivi attributes.

Demo1:
Use an instance of a credential type for each of the `pensioenUitvoerder`/period combinations. This (I think) has the downside it will not be possible to ask the user to disclose information for a specific period.

Demo2:
Use only singleton credential types to ensure that the user can not (by accident) disclose information of an irrelevant period. This has the downside that there can only be a fixed number of periods, and attributes will contain lists instead of single values, so the user will disclose that complete list.

**Comment by stanvanlier** [comment]
Hi @ivard, Do you have suggestions for how this information can be stored as Yivi attributes? Could you otherwise please merge this pull request so I can start experimenting with the two options?

**Comment by ivard** [comment]
The `irma-demo` scheme is loaded in every Yivi app instance, so if we merge PRs here then you can start issuing for demos. 

I quickly scanned your PR and I saw that you requested 20 new demo credentials. This is a bit uncommon request to us. Most new demo issuers start with 1 or 2 credentials. Therefore, I'm not sure that this is the most efficient way to add these attributes to Yivi. We'd like to quickly review the demo setup with you, such that we can look whether we have options for you that might be better suitable for your demo.

You can contact our business developer [Peter Eikelboom](mailto:peter.eikelboom@sidn.nl) for more information.

**Review by ivard — APPROVED** [review]

**Review by bobhageman — APPROVED** [review]

**Pull request merged**
